language: python
python:
  - "2.7"
install:
  - pip install -e .
before_script:
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage
script:
  - nosetests test.py --with-xunit --xunit-file=shippable/testresults/nosetests.xml
  - coverage run --branch test.py
  - coverage xml -o shippable/codecoverage/coverage.xml test.py
